openapi: 3.0.0
info:
  title: Pearl Jam API
  description: API for accessing Pearl Jam related information including albums and music
  version: 1.0.0

servers:
  - url: http://localhost:5000/api

paths:
  /pearljam/album:
    get:
      summary: List all albums
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                type: object
                properties:
                  band:
                    type: string
                  albums:
                    type: array
                    items:
                      $ref: '#/components/schemas/Album'

  /pearljam/album/{album_name}:
    get:
      summary: Get album by name
      parameters:
        - in: path
          name: album_name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  band:
                    type: string
                  album:
                    $ref: '#/components/schemas/Album'
        '404':
          description: Album not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /pearljam/album/id/{id}:
    get:
      summary: Get album by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  band:
                    type: string
                  album:
                    $ref: '#/components/schemas/Album'
        '404':
          description: Album not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /pearljam/album/year/{year}:
    get:
      summary: Get albums by year
      parameters:
        - in: path
          name: year
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  band:
                    type: string
                  albums:
                    type: array
                    items:
                      $ref: '#/components/schemas/Album'
        '404':
          description: No albums found for the year
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /pearljam/integrants:
    get:
      summary: List all integrants
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  band:
                    type: string
                  integrants:
                    type: array
                    items:
                      $ref: '#/components/schemas/Integrant'

  /pearljam/music:
    get:
      summary: List all music
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  band:
                    type: string
                  albums:
                    type: array
                    items:
                      $ref: '#/components/schemas/Album'

  /pearljam/music/year/{year}:
    get:
      summary: Get music by year
      parameters:
        - in: path
          name: year
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  band:
                    type: string
                  year:
                    type: integer
                  music:
                    type: array
                    items:
                      type: string
        '404':
          description: No music found for the year
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /pearljam/music/{music_name}:
    get:
      summary: Get music by name
      parameters:
        - in: path
          name: music_name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  band:
                    type: string
                  music:
                    $ref: '#/components/schemas/Music'
        '404':
          description: Music not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Album:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        year:
          type: integer
        musics:
          type: array
          items:
            $ref: '#/components/schemas/Music'

    Integrant:
      type: object
      properties:
        name:
          type: string
        instrument:
          type: string
        start_year:
          type: integer
        end_year:
          type: string

    Music:
      type: object
      properties:
        name:
          type: string
        track_number:
          type: integer
        album:
          type: object
          properties:
            name:
              type: string
            year:
              type: integer